from pathlib import Path
import subprocess,json
root=Path(__file__).resolve().parent
segments=[
('01-overview','Second Room | Earth Forward',"Second Room is a furniture reuse planner created by Adam Tokar for NextStep Hacks, Earth Forward. This walkthrough uses actual screens from the working browser app, with synthetic narration. The starting question is simple. When a room changes, what can stay useful? Instead of beginning with a shopping list, Second Room begins with furniture you already have. The prototype connects a three dimensional room to decisions, an editable budget, and a practical checklist. The sample starts with five objects, three planned for reuse, one repair, and one new purchase. These are example decisions, not evidence of real environmental impact."),
('02-leave-out','1. Make the decision visible',"Here, the floor lamp has been changed from Buy new to Leave out. The lamp disappears from the room, the included item count drops to four, and the planned budget falls from two hundred and ten euros to thirty five euros. The interface and the calculations share the same plan. Every object can be reused, repaired, replaced, or left out. The point is to make a purchase decision explicit before money is spent. The replacement prices are editable estimates. Leaving an item out also removes it from the comparison baseline, so the app does not count an unnecessary purchase as a saving."),
('03-repair','2. Plan and confirm separately',"Next, the desk repair budget has been edited to fifty euros. The planner updates immediately. The completed checkbox has also been selected for demonstration, so the confirmed count is now one. This is a user reported record, not independent verification that a repair happened. Planning and completion stay separate. Changing an item's action clears its completed state, which prevents an old confirmation from silently carrying over to a new decision. The condition panel also supports notes, rotation, and small position adjustments. The browser preserves the plan after reload, without requiring an account or sending the plan to a server."),
('04-checklist','3. Turn choices into next steps',"The checklist turns the room into concrete next steps. With the lamp excluded, the example replacement baseline is four hundred and fifty five euros. The current repair budget is fifty euros, giving a budget difference of four hundred and five euros. This is a comparison of entered numbers, not verified savings. Each included object gets an action and a completion control where appropriate. A repair remains a task to assess and arrange, not a promise that the item is safe. A downloadable text checklist keeps the plan usable away from the app. JSON export and import provide a portable copy."),
('05-lounge','4. Explore another arrangement',"The Lounge control changes the arrangement while preserving the same reuse decisions. Users can orbit and zoom the room, select furniture, and make bounded adjustments. This is an illustrative planning tool, not a measured floor plan or a collision aware design system. The five procedural objects are original scene assets. No stock furniture models or hidden paid service are required. Condition based suggestions are ordinary transparent rules: ready items can be reused, items needing repair get a repair action, and unsuitable items are left out. Applying suggestions clears completion so users review the new plan."),
('06-mobile','5. Keep the plan accessible',"The responsive version stacks the room and the controls for a phone sized screen. The planner is usable without signing up, installing software, or providing personal information. The room also has labeled controls for changing furniture choices without relying on canvas selection. Local storage keeps the current plan on this device. Export is the way to keep a separate copy. This prototype still needs real user testing, broader accessibility evaluation, and support for users adding their own furniture. Those are future steps, not capabilities being claimed in this demonstration."),
('07-method','Methods, source and next steps',"The public methods page explains every number and limitation. The European Environment Agency supports the general motivation of extending product lifetimes through reuse and repair; it does not validate an impact figure for this app. Second Room was built on September eighth with Codex assisted implementation. It extends the author's original Roomcraft scene created earlier that day, and discloses that reuse openly. The React and Three.js source is public under the MIT license. Seven automated tests cover the plan logic, alongside local and deployed browser checks. The next step is a small user study comparing actual reuse decisions. Try the live prototype and inspect the source through the submission links.")]
clips=[]; elapsed=0; subtitles=[]
for idx,(name,title,script) in enumerate(segments):
    (root/f'{name}.txt').write_text(script)
    subprocess.run(['/usr/bin/say','-v','Samantha','-r','155','-f',str(root/f'{name}.txt'),'-o',str(root/f'{name}.aiff')],check=True)
    duration=float(subprocess.check_output(['/opt/homebrew/bin/ffprobe','-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',str(root/f'{name}.aiff')]))+1
    (root/f'{name}-title.txt').write_text(title)
    vf="scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=0xf4f1e9"
    subprocess.run(['/opt/homebrew/bin/ffmpeg','-y','-loglevel','error','-loop','1','-framerate','24','-i',str(root/f'{name}.png'),'-i',str(root/f'{name}.aiff'),'-vf',vf,'-af','apad','-t',str(duration),'-c:v','libx264','-preset','veryfast','-crf','21','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k',str(root/f'{name}.mp4')],check=True)
    clips.append(f"file '{name}.mp4'");elapsed+=duration
(root/'concat.txt').write_text('\n'.join(clips))
subprocess.run(['/opt/homebrew/bin/ffmpeg','-y','-loglevel','error','-f','concat','-safe','0','-i',str(root/'concat.txt'),'-c','copy','-movflags','+faststart',str(root/'second-room-demo.mp4')],check=True)
(root/'script.json').write_text(json.dumps(segments,indent=2))
print(json.dumps({'duration_seconds':elapsed,'file':str(root/'second-room-demo.mp4')}))
