import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {mountRoom} from './scene.js';
import {ACTIONS,CONDITIONS,initialPlan,normalize,updateItem,totals,suggest,checklist,toScene,serialize,parsePlan,report} from './plan.js';
import './style.css';
const KEY='second-room-v1';
const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
function load(){try{const data=localStorage.getItem(KEY);return data?normalize(JSON.parse(data)):initialPlan();}catch{return initialPlan();}}
function Icon({type}){const paths={cube:<><path d="m12 2 9 5v10l-9 5-9-5V7l9-5Z"/><path d="m3 7 9 5 9-5M12 12v10"/></>,home:<path d="m3 10 9-8 9 8v11h-7v-7h-4v7H3Z"/>,full:<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,tool:<><path d="m14 6 4 4 3-3a6 6 0 0 1-8 7l-7 7-3-3 7-7a6 6 0 0 1 7-8l-3 3Z"/></>};return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[type]}</svg>;}
function saveFile(name,content,type){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function Scene({plan,setPlan,thumbs,setThumbs,api}){
 const host=useRef(),stage=useRef();const [error,setError]=useState('');
 useEffect(()=>{try{api.current=mountRoom(host.current,selected=>setPlan(p=>({...p,selected})),images=>setThumbs(images||{}));api.current.update(toScene(plan));api.current.visibility(plan.items);}catch(e){setError('This browser could not start the 3D view. The complete reuse planner still works below.');console.error(e);}return()=>api.current?.dispose();},[]);
 useEffect(()=>{api.current?.update(toScene(plan));api.current?.visibility(plan.items);},[plan]);
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.current.requestFullscreen)await stage.current.requestFullscreen();}catch{setError('Full-screen is unavailable. You can still use the room below.');}}
 return <section ref={stage} className="stage" aria-label="Interactive 3D room"><div className="webgl" ref={host}/><div className="stage-toolbar"><div className="segments" aria-label="Room layout">{['Studio','Lounge'].map(layout=><button key={layout} aria-pressed={plan.layout===layout} onClick={()=>setPlan(p=>({...p,layout}))}>{layout}</button>)}</div><div className="camera-controls"><button aria-label="Reset camera" onClick={()=>api.current?.home()}><Icon type="home"/></button><button aria-label="Full screen" onClick={fullscreen}><Icon type="full"/></button></div></div>{error&&<p role="alert" className="render-error">{error}</p>}<p className="scene-help">Drag to orbit · Scroll to zoom · Select furniture</p></section>;
}
function Inventory({plan,setPlan,thumbs}){return <div className="inventory" role="radiogroup" aria-label="Furniture">{plan.items.map(i=><button role="radio" aria-checked={plan.selected===i.name} aria-label={`${i.name}, ${i.action}`} key={i.name} className="item" onClick={()=>setPlan(p=>({...p,selected:i.name}))}>{thumbs[i.name]?<img src={thumbs[i.name]} alt=""/>:<span className="thumb-space"/>}<span className="item-name">{i.name}</span><span className={i.action==='Buy new'?'action buy':'action'}>{i.action}</span><span className="radio-dot"/></button>)}</div>;}
function Inspector({plan,setPlan,thumbs}){
 const t=totals(plan),item=plan.items.find(i=>i.name===plan.selected),patch=p=>setPlan(old=>updateItem(old,item.name,p));
 return <aside className="inspector" aria-label="Reuse plan"><h2>Your reuse plan</h2><div className="metrics"><div><strong data-testid="reuse-count">{t.reuse} / {t.included}</strong><span>Reuse planned</span></div><div><strong data-testid="budget">{euro(t.planned)}</strong><span>Budget needed</span></div><div><strong data-testid="confirmed-count">{t.completed}</strong><span>Confirmed reused</span></div></div><Inventory {...{plan,setPlan,thumbs}}/><section className="selected"><h3>Selected: {item.name}</h3><label className="field">Action<select aria-label="Action" value={item.action} onChange={e=>patch({action:e.target.value})}>{ACTIONS.map(a=><option key={a}>{a}</option>)}</select></label>{item.action==='Repair'&&<label className="field">Repair budget (€)<input aria-label="Repair budget (€)" type="number" min="0" max="100000" step=".01" value={item.repair} onChange={e=>patch({repair:e.target.value})}/></label>}<label className="field">Replacement price (€)<input aria-label="Replacement price (€)" type="number" min="0" max="100000" step=".01" value={item.replacement} onChange={e=>patch({replacement:e.target.value})}/></label><label className="field completed-label">Confirmed completed<span><input aria-label="Mark as completed" type="checkbox" checked={item.completed} disabled={!['Reuse','Repair'].includes(item.action)} onChange={e=>patch({completed:e.target.checked})}/>Mark as completed</span></label><details><summary>Condition, position & notes</summary><label className="stack">Condition<select value={item.condition} onChange={e=>patch({condition:e.target.value})}>{CONDITIONS.map(c=><option key={c}>{c}</option>)}</select></label><label className="stack">Rotation: {item.rotation}°<input aria-label="Rotation" type="range" min="-180" max="180" step="15" value={item.rotation} onChange={e=>patch({rotation:Number(e.target.value)})}/></label><div className="movement"><button disabled={item.x<=-.7} onClick={()=>patch({x:Math.round((item.x-.2)*100)/100})}>Move left</button><button disabled={item.x>=.7} onClick={()=>patch({x:Math.round((item.x+.2)*100)/100})}>Move right</button></div><label className="stack">Plan notes<textarea maxLength="500" value={item.note} onChange={e=>patch({note:e.target.value})}/></label><p className="small">Condition and completion are your own records. Movement is illustrative, without collision detection.</p></details></section></aside>;
}
function PlanDialog({dialog,plan,setPlan,message,setMessage}){
 const file=useRef();const t=totals(plan);const tasks=checklist(plan);
 async function importPlan(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>65536)throw Error('Plan must be smaller than 64 KB.');setPlan(parsePlan(await f.text()));setMessage('Plan imported.');}catch(err){setMessage(`Import failed: ${err.message}`);}}
 return <dialog ref={dialog} aria-labelledby="checklist-title"><div className="modal-header"><div><h2 id="checklist-title">From a room to a reuse plan.</h2><p>Make the decision. Take the next step.</p></div><button aria-label="Close checklist" onClick={()=>dialog.current.close()}><Icon type="close"/></button></div><label className="stack">Plan name<input maxLength="80" value={plan.title} onChange={e=>setPlan(p=>({...p,title:e.target.value}))}/></label><div className="budget-summary"><div><span>Replace everything included</span><strong>{euro(t.baseline)}</strong></div><div><span>Your planned budget</span><strong>{euro(t.planned)}</strong></div><div><span>Budget difference</span><strong>{euro(t.difference)}</strong></div></div><p className="small">Editable example prices, not shop quotes. Reuse is planned until you confirm it. The budget excludes transport and other costs unless you include them in your inputs.</p><ol className="tasks">{tasks.map(task=><li key={task.name}><div className="task-title"><strong>{task.name}</strong><span>{task.action} · {euro(task.cost)}</span></div><p>{task.task}</p>{task.note&&<p className="note">{task.note}</p>}{['Reuse','Repair'].includes(task.action)&&<label className="task-done"><input type="checkbox" aria-label={`${task.name} completed`} checked={task.completed} onChange={e=>setPlan(p=>updateItem(p,task.name,{completed:e.target.checked}))}/>I have completed this reuse or repair</label>}</li>)}</ol><div className="dialog-actions"><button onClick={()=>{setPlan(suggest(plan));setMessage('Suggested actions from your condition records. Completion was cleared; review the plan.');}}>Suggest from condition</button><button onClick={()=>file.current.click()}>Import plan</button><input className="file" ref={file} type="file" accept=".json,application/json" onChange={importPlan}/><button className="primary" onClick={()=>{saveFile('second-room-checklist.txt',report(plan),'text/plain');setMessage('Checklist downloaded.');}}>Download checklist</button></div><p role="status">{message}</p></dialog>;
}
function App(){
 const [plan,setPlan]=useState(load),[thumbs,setThumbs]=useState({}),[message,setMessage]=useState('');const api=useRef(),dialog=useRef();
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(plan));}catch{setMessage('Your browser cannot save locally. Export the plan to keep it.');}},[plan]);
 const first=plan.items.find(i=>i.action==='Repair'&&!i.completed)||plan.items.find(i=>i.action==='Reuse'&&!i.completed);const t=totals(plan);
 return <div className="app"><header><a href="/" className="brand"><Icon type="cube"/>Second Room</a><span className="tagline">Plan a room. Keep what works.</span><div className="header-actions"><button onClick={()=>{setPlan(initialPlan());api.current?.home();setMessage('Example plan restored.');}}>Reset</button><button className="primary" onClick={()=>{saveFile('second-room-plan.json',serialize(plan),'application/json');setMessage('Plan exported.');}}>Export plan</button></div></header><main className="workspace"><div className="visual"><section className="intro"><h1>A new space. Less new stuff.</h1><p>See what you can reuse before you buy.</p></section><Scene {...{plan,setPlan,thumbs,setThumbs,api}}/><p className="example">Example plan · Edit the figures for your room. No carbon estimates.</p></div><Inspector {...{plan,setPlan,thumbs}}/><section className="next-step" aria-label="Next step"><h2>The next step</h2><div className="next-icon"><Icon type="tool"/></div><p>{first?<><strong>{first.action} {first.name.toLowerCase()}</strong> — {first.action==='Repair'?'assess and arrange a suitable repair':'check condition and measurements'}</>:t.buy?'Check second-hand options before buying.':'Your reuse checklist is complete.'}</p><button className="primary" onClick={()=>dialog.current.showModal()}>View checklist</button></section></main><div className="feedback" role="status">{message}</div><footer><p>Original project by Ádám Tokár · Built for Earth Forward · <a href="about.html">How it works & sources</a></p><p>Saved on this device · No sign-up or tracking</p></footer><PlanDialog {...{dialog,plan,setPlan,message,setMessage}}/></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
